mingle: remove unused 'total_wgt' in 'agglomerative_ink_bundling_internal'
The CMake macOS CI job has begun erroring out:

  …/lib/mingle/agglomerative_bundling.cpp:400:27: error: variable 'total_wgt'
    set but not used [-Werror,-Wunused-but-set-variable]
  double eps = 0., wgt, total_wgt = 0;
                        ^

While the error is accurate, nothing has changed on our side that would have
caused this. I can only assume Gitlab have upgraded the macOS runners to pull in
a new version of Clang.