gvc: remove multiple declarations of two functions from gvcproc.h
These are already declared in gvc.h with Windows storage-class
attributes.

Without this change, an upcoming commit that defines GVDLL also for
CMake builds, would cause the following errors with native Windows:

C:\Users\magja\graphviz\lib\gvc/gvc.h(67,13): error C2375: 'gvLayoutJobs': redefinition; different linkage [C:\Users\magja\graphviz\build\lib\gvc\gvc.vcxproj]
C:\Users\magja\graphviz\lib\gvc/gvcproc.h(117): message : see declaration of 'gvLayoutJobs' [C:\Users\magja\graphviz\build\lib\gvc\gvc.vcxproj]
C:\Users\magja\graphviz\lib\gvc/gvc.h(91,13): error C2375: 'gvFreeLayout': redefinition; different linkage [C:\Users\magja\graphviz\build\lib\gvc\gvc.vcxproj]
C:\Users\magja\graphviz\lib\gvc/gvcproc.h(116): message : see declaration of 'gvFreeLayout' [C:\Users\magja\graphviz\build\lib\gvc\gvc.vcxproj]