common: remove multiple declaration of attach_attrs from utils.h
This function is already declared in the public gvc.h.

Without this change, an upcoming commit that defines GVDLL also for
CMake builds, would cause the following error with native Windows:

C:\Users\magja\graphviz\lib\gvc/gvc.h(75,14): error C2375: 'attach_attrs': redefinition; different linkage [C:\Users\magja\graphviz\build\lib\common\common_obj.vcxproj]
C:\Users\magja\graphviz\lib\common\utils.h(39): message : see declaration of 'attach_attrs' [C:\Users\magja\graphviz\build\lib\common\common_obj.vcxproj]