cgraph: include config.h in agxbuf.h to get GVDLL in autotools builds
An upcoming commit which changes agxbuf.h to use GVDLL to control the
storage-class attribute declarations would otherwise cause errors like
this:

C:\Users\magja\graphviz\lib\gvc/gvplugin.c:386: undefined reference to `__imp_agxbprint'

Towards https://gitlab.com/graphviz/graphviz/-/issues/2173.