edgepaint: remove unused 'nnodes' in 'node_distinct_coloring'
The CMake macOS CI job has begun erroring out:

  …/lib/edgepaint/node_distinct_coloring.c:204:17: error: variable 'nnodes'
    set but not used [-Werror,-Wunused-but-set-variable]
  int i, j, jj, nnodes = 0;
                ^

While the error is accurate, nothing has changed on our side that would have
caused this. I can only assume Gitlab have upgraded the macOS runners to pull in
a new version of Clang.