cgraph: fix: avoid designated initializers in generic list
MSVC errors when seeing these included in C++ code:

  lib\common/globals.h(36,1): error C7555: use of designated initializers
    requires at least '/std:c++20' [build\lib\mingle\libmingle.vcxproj]
  lib\common/globals.h(36,1): error C4576: a parenthesized type followed by an
    initializer list is a non-standard explicit type conversion syntax
    [build\lib\mingle\libmingle.vcxproj]
  lib\common/globals.h(36,1): error C7555: use of designated initializers
    requires at least '/std:c++20' [build\lib\mingle\libmingle.vcxproj]
  lib\common/globals.h(36,1): error C4576: a parenthesized type followed by an
    initializer list is a non-standard explicit type conversion syntax
    [build\lib\mingle\libmingle.vcxproj]
  lib\common/globals.h(36,1): error C7555: use of designated initializers
    requires at least '/std:c++20' [build\lib\mingle\libmingle.vcxproj]

This breakage was silently introduced in
bbfdc7c7468dd4bfe2dcaeeb2cea99b9f82c76b9.

Gitlab: fixes #2364