gvconfig_libdir: fix const-correctness of char pointers in macOS code
Commit 284df35236e258a49b86fad6f0d062bf0c2fa840 changed the source pointer `tmp`
used here to be `const`. A side effect of this was introducing a warning
breaking the CMake build on macOS:

  lib/gvc/gvconfig.c:329:10: error: initializing 'char *' with an expression of
    type 'const char *' discards qualifiers
    [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                        char* s = tmp-1;
                              ^   ~~~~~

This commit was merged via !2231 whose source branch did not have permission to
use the macOS shared runners, so this issue was not caught in pre-merge CI.