tred: MSBuild: add pathplan include directory
An upcoming commit that changes tred.c to include utils.h instead of
timing.h would otherwise cause this error:

C:\Users\magja\graphviz\lib\common\types.h(33,10): fatal error C1083: Cannot open include file: 'pathgeom.h': No such file or directory