mingle: remove unused 'len_total' in 'pedge_export_gv'
The CMake macOS CI job has begun erroring out:

  …/lib/mingle/edge_bundling.cpp:208:27: error: variable 'len_total' set but not
    used [-Werror,-Wunused-but-set-variable]
    double maxwgt = 0, len, len_total, len_total0;
                            ^

While the error is accurate, nothing has changed on our side that would have
caused this. I can only assume Gitlab have upgraded the macOS runners to pull in
a new version of Clang.