neatogen: remove unused 'total_gap' in 'constrained_majorization_new_with_gaps'
The CMake macOS CI job has begun erroring out:

  …/lib/neatogen/quad_prog_solve.c:602:11: error: variable 'total_gap' set but
    not used [-Werror,-Wunused-but-set-variable]
    float total_gap, target_place;
          ^

While the error is accurate, nothing has changed on our side that would have
caused this. I can only assume Gitlab have upgraded the macOS runners to pull in
a new version of Clang.