tred: autotools: link to the shared gvc lib instead of the static common lib
The common lib is built into the gvc lib.

An upcoming commit that changes tred.c to include utils.h instead of
timing.h would otherwise cause these errors:

/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: tred.o: in function `process':
/cygdrive/c/GitLab-Runner/builds/magjac/graphviz/cmd/tools/tred.c:296: undefined reference to `__imp_start_timer'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/GitLab-Runner/builds/magjac/graphviz/cmd/tools/tred.c:299: undefined reference to `__imp_elapsed_sec'