tred: CMake: link to the gvc lib instead of the common lib
The common lib is a static lib which is built into the shared gvc lib.

An upcoming commit that changes tred.c to include utils.h instead of
timing.h would otherwise cause these errors:

C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cmd/tools/CMakeFiles/tred.dir/tred.c.obj:tred.c:(.text+0xb47): undefined reference to `__imp_start_timer'
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cmd/tools/CMakeFiles/tred.dir/tred.c.obj:tred.c:(.text+0xb7a): undefined reference to `__imp_elapsed_sec'