pack: CMake: set also _BLD_gvc
This is a temporary measure until an upcoming commit series cleans up
the control of the Windows storage-class attributes.

Without this change, an upcoming commit that defines GVDLL also for
CMake builds, would cause many errors like this with minGW:

pack/CMakeFiles/pack_obj.dir/ccomps.c.obj:ccomps.c:(.text+0x1c95): undefined reference to `__imp_Verbose'