common: fix incorrect printf format code for 'uint16_t' column addition
The addition of two `uint16_t` values promotes to `int` (on platforms with an
`int` wider than 16 bits), so the format code here was incorrect. This surfaced
as a build error on macOS:

  lib/common/htmltable.c:1423:39: error: format specifies type 'unsigned short'
    but the argument has type 'int' [-Werror,-Wformat]
        agxbprint(&value_buffer, "%" PRIu16, cp->col + cp->colspan);
                                  ~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~~

This reverts part of 72ce5bcf28f904e9efd3aed85578dcebb473af1d.