CI: upgrade Git on CentOS 7
Git 2.36.1 seems no longer installable on CentOS 7:

  Error: Package: git236-2.36.1-2.el7.ius.x86_64 (/git236-2.36.1-2.el7.ius.x86_64)
             Requires: git-core = 2.36.1-2.el7.ius
             Available: git-1.8.3.1-23.el7_8.x86_64 (base)
                 git-core = 1.8.3.1-23.el7_8
             Available: git236-core-2.36.2-1.el7.ius.x86_64 (ius)
                 git-core = 2.36.2-1.el7.ius
             Available: git236-core-2.36.3-1.el7.ius.x86_64 (ius)
                 git-core = 2.36.3-1.el7.ius
             Available: git236-core-2.36.4-1.el7.ius.x86_64 (ius)
                 git-core = 2.36.4-1.el7.ius
  Error: Package: git236-2.36.1-2.el7.ius.x86_64 (/git236-2.36.1-2.el7.ius.x86_64)
             Requires: git-core-doc = 2.36.1-2.el7.ius
             Available: git236-core-doc-2.36.2-1.el7.ius.noarch (ius)
                 git-core-doc = 2.36.2-1.el7.ius
             Available: git236-core-doc-2.36.3-1.el7.ius.noarch (ius)
                 git-core-doc = 2.36.3-1.el7.ius
             Available: git236-core-doc-2.36.4-1.el7.ius.noarch (ius)
                 git-core-doc = 2.36.4-1.el7.ius
  Error: Package: git236-2.36.1-2.el7.ius.x86_64 (/git236-2.36.1-2.el7.ius.x86_64)
             Requires: perl-Git = 2.36.1-2.el7.ius
             Available: git236-perl-Git-2.36.2-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.2-1.el7.ius
             Available: git236-perl-Git-2.36.3-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.3-1.el7.ius
             Available: git236-perl-Git-2.36.4-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.4-1.el7.ius
             Available: perl-Git-1.8.3.1-23.el7_8.noarch (base)
                 perl-Git = 1.8.3.1-23.el7_8
  Error: Package: git236-2.36.1-2.el7.ius.x86_64 (/git236-2.36.1-2.el7.ius.x86_64)
             Requires: perl-Git = 2.36.1-2.el7.ius
             Available: git236-perl-Git-2.36.2-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.2-1.el7.ius
             Available: git236-perl-Git-2.36.3-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.3-1.el7.ius
             Installing: git236-perl-Git-2.36.4-1.el7.ius.noarch (ius)
                 perl-Git = 2.36.4-1.el7.ius
             Available: perl-Git-1.8.3.1-23.el7_8.noarch (base)
                 perl-Git = 1.8.3.1-23.el7_8