common: fix incorrect printf format code for 'uint16_t' row addition
The addition of two `uint16_t` values promotes to `int` (on platforms with an
`int` wider than 16 bits), so the format code here was incorrect. This surfaced
as a build error on macOS:

  lib/common/htmltable.c:1429:39: error: format specifies type 'unsigned short'
    but the argument has type 'int' [-Werror,-Wformat]
        agxbprint(&value_buffer, "%" PRIu16, cp->row + cp->rowspan);
                                  ~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~~

This reverts part of 13af74539640ddf75ac2cc6a2c59dd0444cc50e4.