common: CMake: specify include directory of expat
A build system should not rely on the existence of 3rd party
library/header files in standard prefixes as one might want to compile
and link against a patched build or a custom install in some
non-standard location. This is also helpful for developers who rely on
package managers like Conda or Spack for their daily development.

If expat is a dep, we need to pass -I/path/containing/expat.h to the
compiler while compiling the source files of the target 'common_obj',
without which, one can face the following issue:

graphviz/lib/common/htmllex.c:28:10: fatal error: expat.h: No such file or directory
   28 | #include <expat.h>
      |          ^~~~~~~~~
compilation terminated.