tests: fix missing #include
The default toolchain on Ubuntu 22.10 comes with a slightly more pedantic header
layout:

  [ 87%] Building CXX object tests/CMakeFiles/test_common.dir/svg_element.cpp.o
  tests/svg_element.cpp: In member function 'SVG::SVGRect
    SVG::SVGElement::outline_bbox(bool)':
  tests/svg_element.cpp:287:29: error: 'all_of' is not a member of 'std'
    287 |     auto is_vertical = std::all_of(
        |                             ^~~~~~
  tests/svg_element.cpp:290:31: error: 'all_of' is not a member of 'std'
    290 |     auto is_horizontal = std::all_of(
        |                               ^~~~~~