tred: rename DIST macro to avoid shadowing
The next commit in this series will include types.h which transitively
includes geom.h which has another DIST macro defined.

Without this change, this error would occur:

FAILED: cmd/tools/CMakeFiles/tred.dir/tred.c.obj
C:\tools\msys64\mingw64\bin\ccache.exe  gcc -DDEMAND_LOADING=0 -DDIGCOLA -DENABLE_LTDL -DGVDLL -DORTHO -DSFDP -IC:/Users/magja/graphviz/build -IC:/Users/magja/graphviz/lib -IC:/Users/magja/graphviz/cmd/tools -IC:/Users/magja/graphviz/build/cmd/tools -IC:/Users/magja/graphviz/lib/cdt -IC:/Users/magja/graphviz/lib/cgraph -IC:/Users/magja/graphviz/lib/common -IC:/Users/magja/graphviz/lib/gvc -IC:/Users/magja/graphviz/lib/pack -IC:/Users/magja/graphviz/lib/pathplan -Werror -Wall -std=gnu99 -MD -MT cmd/tools/CMakeFiles/tred.dir/tred.c.obj -MF cmd\tools\CMakeFiles\tred.dir\tred.c.obj.d -o cmd/tools/CMakeFiles/tred.dir/tred.c.obj -c C:/Users/magja/graphviz/cmd/tools/tred.c
C:/Users/magja/graphviz/cmd/tools/tred.c:38: error: "DIST" redefined [-Werror]
   38 | #define DIST(ninfo,n) (ninfo[AGSEQ(n)].dist)
      |
In file included from C:/Users/magja/graphviz/lib/common/types.h:31,
                 from C:/Users/magja/graphviz/cmd/tools/tred.c:24:
C:/Users/magja/graphviz/lib/common/geom.h:53: note: this is the location of the previous definition
   53 | #define DIST(p,q)  (sqrt(DIST2((p),(q))))
      |